config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'sessions/new'
  resources :tasks do
    collection do
      post :confirm
    end
  end

  namespace :admin do
    resources :users
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tasks#index'
  resources :sessions, only: %i[new create destroy]
  resources :users, only: %i[new create show edit]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
    has_many :labellings, dependent: :destroy
    has_many :tasks, through: :labellings
end

app/models/labelling.rb
class Labelling < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  validates :name, presence: true
  validates :content, presence: true

  enum priority: { 高: 1, 中: 2, 低: 3 }
  enum status: { 完了: 1, 着手中: 2, 未着手: 3 }

  scope :name_search, ->(text_serach) { where('name LIKE ?', "%#{text_serach}%") }
  scope :status_search, ->(text_serach) { where(status: text_serach) }
  belongs_to :user
  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_destroy :reject_destroy_admin
  before_update :reject_update_admin

  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true, on: :create,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :tasks, dependent: :destroy
  private

  def reject_destroy_admin
    if User.where(admin: true).count == 1
      user = User.where(admin: true)
      throw :abort if user[0] == self
    end
  end

  def reject_update_admin
    if User.where(admin: true).count == 1 && admin == false
      user = User.where(admin: true)
      if user[0] == self
        errors.add(:user, '更新にエラーがあります。現在あなたのみが管理人のため管理人から外れることはできません。')
        throw :abort
      end
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :check_admin
  before_action :set_user, only: %i[show edit destroy update]

  def index
    @users = User.all.order('created_at DESC')
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to(admin_users_path)
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to(admin_users_path)
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to(admin_users_path)
    else
      redirect_to admin_users_path, notice: t('view.user.destroy_errer')
    end
  end

  private

  def check_admin
    if logged_in? # ログインしている場合
      redirect_to(root_path) unless current_user.admin? # adminでなければ、タスク一覧へリダイレクト
    else # ログインしていない場合
      redirect_to(new_session_path) # ログインページへリダイレクト
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :admin, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:danger] = 'ログインしました'
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]
  before_action :login_check, only: %i[index new edit destroy]
  # GET /tasks
  # GET /tasks.json
  def index
    if params[:sort_expired]
      @tasks = current_user.tasks.all.order(end_date: 'DESC').page(params[:page]).per(10)
    elsif params[:sort_priority]
      @tasks = current_user.tasks.all.order(priority: 'ASC').page(params[:page]).per(10)
    elsif
      @tasks = current_user.tasks.all.order(created_at: 'DESC').page(params[:page]).per(10)
    end

    if params[:search].present?
      if params[:name].present? && params[:status].present?
        @tasks = current_user.tasks.name_search(params[:name]).status_search(params[:status]).page(params[:page]).per(10)
      elsif params[:name].present?
        @tasks = current_user.tasks.name_search(params[:name]).page(params[:page]).per(10)
      elsif params[:status].present?
        @tasks = current_user.tasks.status_search(params[:status]).page(params[:page]).per(10)
      end
    end

    @tasks = @tasks.joins(:labels).where(labels: { id: params[:label_id] }) if params[:label_id].present?
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit; end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task = current_user.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def confirm
    @task = current_user.tasks.build(task_params)
    render :new if @task.invalid?
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :content, :end_date, :priority, :status, { label_ids: [] })
  end

  def login_check
      redirect_to new_session_path, notice: t('view.task.login') unless logged_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit]
  before_action :user_check, only: %i[show]
  before_action :login_check, only: %i[new]

  def new
    @user = User.new 
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'ログインしました'
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_check
    redirect_to root_path if current_user != @user
  end

  def login_check
    redirect_to user_path(current_user.id) if logged_in?
  end
end

app/helpers/admin/users_helper.rb
# frozen_string_literal: true

module Admin::UsersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>User edit</h1>

<% if @user.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
        <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
        </ul>
    </div>
<% end %>

<%= form_with(model: [:admin, @user], local: true) do |f| %>  
    <%= f.label :name %>
    <%= f.text_field :name %>
　
    <br><%= f.label :email %>
    <%= f.email_field :email %>

    <br><%= f.label :admin %>
　　<%= f.check_box :admin,{}, "true","false" %>

    <br><%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.submit "Edit my account" %>
<% end %>

app/views/admin/users/index.html.erb
<h1><%= t('view.user.user_lists') %></h1>

<td><%= current_user.id %>:<%= current_user.name %></td>

<table class="table">
    <thead>
        <tr class="table-info">
            <th><%= t('view.user.id') %></th>
            <th><%= t('view.user.name') %></th>
            <th><%= t('view.user.admin') %></th>
            <th><%= t('view.user.task_count') %></th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @users.each do |user| %>
            <tr>
                <td><%= user.id %></td>
                <td><%= user.name %></td>
                <td><%= user.admin %></td>
                <td><%= user.tasks.count %></td>
                <td><%= link_to t('view.task.show_button'), admin_user_path(user) %></td>
                <td><%= link_to t('view.task.edit_button'), edit_admin_user_path(user) %></td>
                <td><%= link_to t('view.task.destroy'), admin_user_path(user), method: :delete, data: { confirm: t('view.user.destroy_confirm') } %></td>
            </tr>  
        <% end %>
    </tbody>
</table>

<p><%= link_to t('view.task.new_button'), new_admin_user_path , class: "btn btn-info", type: "button" %></p>

app/views/admin/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: [:admin, @user], local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>
　
  <br><%= f.label :email %>
  <%= f.email_field :email %>

  <br><%= f.label :admin %>
  <%= f.check_box :admin,{}, "true","false" %>

  <br><%= f.label :password %>
  <%= f.password_field :password %>

  <br><%= f.label :password_Confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/admin/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<% if logged_in? %>
  <% if current_user.id == @user.id %>
    <p><%= link_to 'Edit', edit_user_path(@user) %></p>
  <% end %>
<% end %> 

<p><%= link_to 'task', tasks_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body> 
    <% flash.each do |key, value| %> 
      <%= content_tag(:div, value, class: "#{key}") %> 
    <% end %>

    <%# <nav class= "navbar navbar-dark bg-primary " style="background-color: #e3f2fd;" > %>
      <% if logged_in? %>
        <%= link_to "profile", user_path(current_user.id), class: 'text-light' %>
        <%= link_to "logout", session_path(current_user.id), method: :delete , class: 'text-light' %>
      <% else %>
        <%= link_to "sign up", new_user_path , class: 'text-light' %>
        <%= link_to "login", new_session_path , class: 'text-light' %>
      <% end %>
    </nav>

    <%= yield %> 
  </body>
</html>

app/views/tasks/_editform.html.erb
<%= form_with(model: task, local: true) do |form| %>
    <% if task.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

            <ul>
                <% task.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>

    <div class="field">
        <%= form.label :content %>
        <%= form.text_area :content %>
    </div>

    <div class="field">
        <%= form.label :end_date %>
        <%= form.date_select :end_date %>
    </div>

    <div class="field">
        <%= form.label :priority %>
        <%# <%= form.number_field :priority %> 
        <%= form.select :priority, [["高","高"], ["中","中"], ["低","低"]], include_blank: "選択して下さい" %>
    </div>

    <div class="field">
        <%= form.label :status %>
        <%# <%= form.number_field :status %>
        <%= form.select :status, [["完了","完了"], ["着手中","着手中"], ["未着手","未着手"]], include_blank: "選択して下さい" %>
    </div>

    <div class="field">
        <%= form.collection_check_boxes(:label_ids, Label.all, :id, :name) %>
    </div>


    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%# <%= form.number_field :priority %> 
    <%= form.select :priority, [["高","高"], ["中","中"], ["低","低"]], include_blank: "選択して下さい" %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%# <%= form.number_field :status %>
    <%= form.select :status, [["完了","完了"], ["着手中","着手中"], ["未着手","未着手"]], include_blank: "選択して下さい" %>
  </div>

  <br> <br>
  <div class="field">
    <%= form.collection_check_boxes(:label_ids, Label.all, :id, :name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'editform', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="page-header">
	<h1>タスク検索</h1>
</div>

<p id="notice"><%= notice %></p>

<%= form_with url: tasks_path, method: :get, local: true do |form| %>
  <div class="form-inline">
    <div class="input-group">
      <%= form.label :Name, class:"input-group-addon" %>
      <%= form.text_field :name, class:"form-control" %>
    </div>
  </div>
  <br>
  
  <div class="form-inline">
    <div class="input-group">
      <%= form.label :Status, class:"input-group-addon" %>
      <%= form.select :status, [["完了","1"], ["着手中","2"], ["未着手","3"]], include_blank: "選択して下さい" , class:"caret" %>
    </div>
  </div>
    
    <%= form.hidden_field :search, value: 'true' %>

  <br>
  <div class="form-inline">
    <div class="btn-group" >
      <%= form.submit 'Search', class:"btn btn-default"%>
    </div>
  </div>
<% end %>

<br>
<%= form_with url: tasks_path, method: :get, local: true do |form| %>
  <%= form.select("label_id", Label.pluck(:name, :id), { include_blank: true }) %>
  <%= form.submit '検索', name: nil %>
<% end %>

<br>
<%= link_to "終了期限でソートする", tasks_path(sort_expired: "true"), class:"btn btn-primary active" %>
<%= link_to "優先順位でソートする", tasks_path(sort_priority: "true"), class:"btn btn-primary active" %>
<%= link_to "リセット", tasks_path, class:"btn btn-primary active" %>

<br>
<br>
<div class="page-header">
	<h1>タスク一覧</h1>
</div>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th>End date</th>
      <th>Priority</th>
      <th>Status</th>
      <th>Label</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td class="task_row"><%= task.name %></td>
        <td><%= task.content %></td>
        <td class="date_row"><%= task.end_date %></td>
        <td class="priority_high"><%= task.priority %></td>
        <td><%= task.status %></td>
        <td><% task.labels.each do |label| %>
            <%= label.name %>
          <% end %>
        </td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @tasks %>
<br>

<%= link_to 'New Task', new_task_path, class:"btn btn-primary active"%>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<p>
  <strong>End date:</strong>
  <%= @task.end_date %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Label</strong>
  <% @task.labels.each do |label| %>
    <%= label.name %>
  <% end %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/edit.html.erb
<h1>User edit</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>
　
  <br><%= f.label :email %>
  <%= f.email_field :email %>

  <%# <br><%= f.label :image %>
  <%# <%= f.file_field :image %>
    <!-- ↓一時的なデータとしてファイル構造を含むデータをキャッシュする -->
  <%# <%= f.hidden_field :image_cache%> 
  
  <br><%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit "Edit my account" %>

  
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>
　
  <br><%= f.label :email %>
  <%= f.email_field :email %>

  <br><%= f.label :password %>
  <%= f.password_field :password %>

  <br><%= f.label :password_Confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<% if logged_in? %>
  <% if current_user.id == @user.id %>
    <p><%= link_to 'Edit', edit_user_path(@user) %></p>
  <% end %>
<% end %> 
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th>End date</th>
      <th>Priority</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user.tasks.each do |task| %>
      <tr>
        <td class="task_row"><%= task.name %></td>
        <td><%= task.content %></td>
        <td class="date_row"><%= task.end_date %></td>
        <td class="priority_high"><%= task.priority %></td>
        <td><%= task.status %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to 'task', tasks_path %></p>